# Generated by Django 3.1.2 on 2021-07-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(max_length=100),
        ),
    ]
